---
glob: "**/*.erb"
exclude:
  - '**/vendor/**/*'
  - 'test/fixtures/**'
linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'text/javascript'
      - 'application/ld+json'
    allow_blank: false
    disallow_inline_scripts: false
  NoJavascriptTagHelper:
    enabled: false
  Rubocop:
    enabled: true
    exclude:
      - "**/vendor/**/*"
      - "**/vendor/**/.*"
      - "bin/**"
      - "db/**/*"
      - "config/**/*"
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      AllCops:
        DisabledByDefault: true
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Rails/SaveBang:
        Enabled: false
