# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

module Rails
  def self.root
    if caller.first.include? "rails_translation_manager"
      Pathname.new(Dir.pwd.to_s.sub("/spec/dummy", ""))
    else
      Pathname.new(Dir.pwd)
    end
  end
end

Rails.application.load_tasks
