# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

module Rails
  def self.root
    Pathname.new(Dir.pwd.to_s.sub("/spec/dummy", ""))
  end
end

Rails.application.config.root = Rails.root

Rails.application.load_tasks
