# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

module Rails
  def self.root
    if caller[0].include? "rails_translation_manager"
      overridden_root = Pathname.new(Dir.pwd.to_s.sub("/spec/dummy", ""))
      Rails.application.config.root = overridden_root
      overridden_root
    else
      Pathname.new(Dir.pwd)
    end
  end
end

Rails.application.load_tasks
